### ISSUE TITLE
App connects to Google Analytics

### ISSUE THREAD

**Issue by working-name** [httptoolkit/httptoolkit-desktop#26]
![Screen Shot 2021-05-16 at 1 38 02 PM](https://user-images.githubusercontent.com/16505052/118406916-29ccf600-b64c-11eb-81a3-3bc9ef8dc07e.png)

**Comment by pimterry** [comment]
Thanks for the feedback. Yes, GA is used for tracking basic telemetry in a few places: mainly the total number of users, app performance, and core events (e.g. what percentage of Firefox interceptions succeed/fail). There's more details on external services the HTTP Toolkit talks to in https://httptoolkit.tech/privacy-policy/. That said:

* This is anonymous throughout - IP anonymization is enabled, no other user data is ever sent to GA, and it couldn't be used to track you either by cookie or fingerprinting anyway since it's entirely outside of your normal browser.
* If you want to actively block it for yourself, as using separate tools as here or by using a browser with an ad blocker, that will work totally fine.
* If you use HTTP Toolkit in a browser with DNT enabled, GA is disabled.
* In future, I'm definitely interested in migrating to a non-Google platform for this, but they're generally not free (which is problematic for a small open-source project) and they're designed for basic website metrics, rather than the kind of event analytics that apps need.

Many valuable fixes have come from issues directly visible in analytics, and it's a strong force in deciding what features to build next. It's a debatable position and there are absolutely tradeoffs, but personally I would find it extremely difficult to develop and maintain software blind, with no reliable feedback for core metrics like these.

That's the goal here: useful telemetry but retaining as much anonymity as possible throughout. I've just been through to check to ensure that the above is true everywhere (thanks for the nudge there). If you spot anywhere where it's not  - e.g. anything that breaks because GA is blocked - then do let me know.

**Comment by working-name** [comment]
Hello! Thank you for the amazingly detailed response which you do not owe anyone. I appreciate the care you put into it especially as it pertains to people's privacy.
