### ISSUE TITLE
Error with 3221225785

### ISSUE THREAD

**Issue by hechunjun123** [httptoolkit/httptoolkit-desktop#41]
windows 7 home edition 64bit

result: server shutdown unexpectedly with code 3221225785

**Comment by pimterry** [comment]
Windows 7 is not supported - see https://github.com/httptoolkit/httptoolkit/issues/243.

This is unavoidable unfortunately, because Windows 7 is not supported by many tools and components we use (including Node.js) which makes it impossible to keep working nowadays.

Windows 7 is also not supported or maintained by Microsoft since January 2020, and has many serious security issues. You should upgrade to at least Windows 8.1 as soon as possible.
