### ISSUE TITLE
Error on Windows 7

### ISSUE THREAD

**Issue by AKGravesen** [httptoolkit/httptoolkit-desktop#44]
I've installed HTTP Toolkit on Windows 7*64 and after launching got error
![chrome_ciPmjUWsDG](https://user-images.githubusercontent.com/109067202/178220626-a34964b9-fd7c-4267-ac8b-cfba5035066d.png)

Could someone help me please?

**Comment by pimterry** [comment]
Hi @AKGravesen, thanks for your message. See https://github.com/httptoolkit/httptoolkit/issues/243 - this error is because Windows 7 is not supported.

It's been officially end-of-life and unsupported by Microsoft for a few years now, and it's recently become completely incompatible with many components that HTTP Toolkit uses internally, so it's now impossible to make it work correctly there.

I would strongly recommend upgrading - not only will lots of software not work on Windows 7, there's also many well known security holes there that will never be fixed.

**Comment by T3rm1** [comment]
> I would strongly recommend upgrading - not only will lots of software not work on Windows 7, there's also many well known security holes there that will never be fixed.

Are there any old versions that still support Windows 7. I also need it. Support for Windows 7 is still available until Feb 2023 with ESU and recent news even indicate that Windows 7 will get another 3 years of support. Also it's just not true that "lots of software" does not work on Windows 7. In fact the opposite is true and the vast majority does still work.

**Comment by pimterry** [comment]
> Are there any old versions that still support Windows 7

I'm afraid not, no.

Old versions will always automatically update to the latest version, for security & compatibility reasons. HTTP Toolkit is quite integrated into other apps and quite security-sensitive software - it directly interacts with your root certificate stores to manage trust in your applications, runs commands as root on android devices, and has full control over network connections - and it's not safe or in any way supported to run outdated versions on purpose.

Even if you could, many of them wouldn't work usefully for most cases anyway, since integrations require constant updates to remain compatible with new versions of browsers, new Android OS releases, and tightening HTTPS certificate requirements.

The core issue is that Node.js dropped support in v14, released in April 2020. Other runtimes including Python completely dropped support in 2020 too. Even the latest versions of Microsoft's own Visual Studio & VS Code do not officially support Windows 7.

At the end of the day, there's simply nothing I can do about this. HTTP Toolkit depends on Node.js. I've continued using older LTS versions for wider support as long as possible, but they're now no longer supported either, and have major breaking issues that we can't mitigate. I'm sorry, but it's simply not possible to continue any longer.

If you'd like support for Windows 7, you will need to either persuade the Node.js team to bring back support (imo very unlikely unless you're willing to pay for a full-time team of maintainers to do all the development work to do so) or fork the full HTTP Toolkit project and maintain your own self-hosted version using outdated versions of Node (and likely other dependencies). You're entirely welcome to do so of course, it's all open source, but be aware that this will bring back quite a few bugs that are unfixable without modern Node - notably including significant memory leaks and intermittent segfaults when intercepting any HTTP/2 traffic.

**Comment by T3rm1** [comment]
Thank you for your detailed answer. If anyone comes across this issue and searches for a web debugging proxy for Windows 7, I was able to use Fiddler Classic for my goal.

I just want to point out a few things because you said you stayed on LTS releases for better compatibility:

- Python 3.8 is still supported until October 2024 and officially supports Windows 7
- Node 12 was supported until April 2022 and officially supports Windows 7
- Node 14.16 is not officially supported on Windows 7 but still works. The latest v14 does not work though.

Anyway, I fully understand that with Node 12 being EOL now that you don't support Windows 7 any more.
