### ISSUE TITLE
Getting error Unable to verify the first certificate

### ISSUE THREAD

**Issue by saisandeepvaddi** [httptoolkit/httptoolkit-desktop#7]
![image](https://user-images.githubusercontent.com/13838175/64998655-023fec00-d8b3-11e9-8fac-1330ae7b2bb0.png)

**Comment by saisandeepvaddi** [comment]
Thanks for the cool tool. 
I use a lot of localhost and 192.x.x.x. Is there a way to check internal network traffic.

**Comment by pimterry** [comment]
Localhost & local network traffic should work like any other traffic, for plain HTTP requests.

For HTTPS it's a different matter, and it looks like that's what's happening here. Are you using HTTPS on that 192.168.1.60 server, presumably with a self-signed certificate? If so that's the issue here: the connection is going through, but HTTP Toolkit is finding a self-signed certificate, which can't be trusted by default. That's allowed by default for `localhost`, but not for any other URLs, since there's a security risk there.

If that's what's happening here, then this is supported by a feature that lives in the Pro settings, so you'll need a Pro account. It looks like this:

![Certificate whitelist screenshot](https://user-images.githubusercontent.com/1526883/65035323-2bab5700-d949-11e9-862d-9bf8a83031c9.png)

If this server isn't supposed to be using HTTPS then there's something completely different going on there. I'm not sure what that would be, but let me know and I can look into it further.

**Comment by saisandeepvaddi** [comment]
What you said is correct. It is using self signed certificate. Thanks for the details.
