### ISSUE TITLE
Configured rules could not be activated, so were reset to default.

### ISSUE THREAD

**Issue by CoolMind** [httptoolkit/httptoolkit-desktop#74]
Hello!

When using Http Toolkit for a long time with Android emulator an error "Configured rules could not be activated, so were reset to default." can appear.

It is usually thrown when Windows turns to sleep mode (hybernate) and restores after some time. Then the emulator continues working, but any press in Http Toolkit leads to this error. The error message can be hidden and after that appears again infinitely. Only Task manager can help.

Could you, please, add a button "Quit" or fix the error?

![HTTP_Toolkit_ibLOka6qrR](https://github.com/user-attachments/assets/6752c867-fae4-4ea7-82ae-91419dcdba81)

**Comment by pimterry** [comment]
It's not clear why, but in some environments (but not all of them - I can't seem to reproduce it myself in testing) the websocket breaks and fails to reconnect after the machine comes back from sleep, and leaves the application in an internally broken state, which triggers this. In most of my testing meanwhile, the connection stops, but then reconnects just fine when the machine resumes.

I'm working on this now. To start with, this is now handled separately from broken rule saving, so that the app will immediately show a clear error and exit any time this happens (e.g. immediately after sleep, if it fails to resume OK).

It won't just be quietly broken until you save a rule later, or show endless alerts, and it won't reset your rules when it exits any more - it'll just close as normal, so you can restart and keep going. It's still very inconvenient, but that should solve the immediate problem with people losing the unsaved rule configuration.

I'm going to improve that UX, and investigate the underlying cause further now. If you can share nay more details about you device configuration (as much info as possible) and when exactly this happens so I can reliably reproduce it myself, that would be very helpful.

**Comment by CoolMind** [comment]
@pimterry Thank you for the detailed answer! I agree with you, our application uses websockets and sometimes doesn't restore them or a server temporarily doesn't connect (for instance, updating backend).
I haven't gotten this error today. My configuration is:

Windows 11 Home Single language (21H2) x64.
i7-12700H, 16 GB RAM.
Android Studio with emulators (Android 10, 11).
HTTP Toolkit 1.19.0, free version.

Probably will send logs if get.

**Comment by CoolMind** [comment]
I still haven't received this error, but got another one twice.

> Server disconnected unexpectedly, app restart required.
> Please report this at github.com/httptoolkit/httptoolkit.

![изображение](https://github.com/user-attachments/assets/b2179481-bcd5-47e9-bd6b-c510958dec8d)

It raises during work (no movements in the emulator, no sleep mode). Here is a log:
[last-run.log](https://github.com/user-attachments/files/17544090/last-run.log)

**Comment by pimterry** [comment]
The above "configured rules could not be activated, so were reset to default" messages should no longer appear, and rules will not be reset, unless there's a real issue with the rules themselves. Instead in this broken-on-wake case you'll see the different explicit error above (see #647) but your rules won't reset. I'm working on fixing that fully so there's no error at all - I'm going to close this to consolidate issues, but keep an eye on #647 for updates.
